# permissions for end users to edit timedscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: timedscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deploy-timed-scaler
    app.kubernetes.io/part-of: deploy-timed-scaler
    app.kubernetes.io/managed-by: kustomize
  name: timedscaler-editor-role
rules:
- apiGroups:
  - scaler.bailu.io
  resources:
  - timedscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scaler.bailu.io
  resources:
  - timedscalers/status
  verbs:
  - get
